name: alibaba-nacos-config-download
rules:
  - method: GET
    path: "/v1/cs/configs?export=true&group=&tenant=&appName=&ids=&dataId="
    expression: |
      response.status == 200
detail:
  author: fliggy